Aida 1936
NextCenturyCorporation/AIDA-Interchange-Format pull request #301
Opened 2021-10-12 17:45 UTC by phile-caci

Hey @eaciv ,

This is branched from AIDA-1932 (since I needed the ontology files generated from Java), so I think you can just PR this one.  Let me know if you want me to cancel that PR.

For invalid_examples.py, I wasn't sure if this was still being used.  Looks like it had older ontology references in them (I updated them).

Let me know if I missed anything.

Thanks!

2021-10-18 15:15 UTC, eaciv requested changes
Everything works as expected. I'm really impressed with how you were able to blend your changes so seamlessly with the existing code. 

I have suggested some changes to the SHACL constraints and the tests. Let me know what you think.

2021-10-19 15:06 UTC, phile-caci commented on java/src/test/java/com/ncc/aif/ExamplesAndValidationTest.java
> +            markType(model, utils.getAssertionUri(), russia, SeedlingOntology.GeopoliticalEntity, system, 1.0);
Removed

2021-10-19 15:06 UTC, phile-caci commented on java/src/test/java/com/ncc/aif/ExamplesAndValidationTest.java
> +        }
Removed

2021-10-19 15:06 UTC, phile-caci commented on python/tests/invalid_examples.py
> +    def test_create_an_event_argument_add_invalid_attribute(self):
Added Test

2021-10-19 17:34 UTC, merged